### PR TITLE
Add copy function

### PR DESCRIPTION
**Pull request by JmzTaylor**

### CODE REVIEW

**Comment by ich777** [comment]
@JmzTaylor I've merged Copy/Snapshot in one column what do you think of that change?
I think there are enough column and buttons on the main page for now... :D

grafik

**Comment by ich777** [comment]
What do you think about to move the `DESTROY` button to the end and also include it in this column like `SNAPSHOT/COPY/DESTROY`

**Comment by JmzTaylor** [comment]
Looks good to me

**Comment by ich777** [comment]
@JmzTaylor will close this PR and merge it manually because have to change a few things too.
Thank you for your contribution! Really much appreciated.

**Pull request closed without merging**
